### ISSUE TITLE
coinmarketcap changed naming 

### ISSUE THREAD

**Issue by iwok** [mess110/coinmarketcap.northpole.ro#37]
I think coinmarketcap changed the naming and added the symbol to the name.

`{"position":"1","name":"BTC\n                        Bitcoin","symbol":"BTC","identifier":"bitcoin","category":"currency","marketCap": .........`

https://coinmarketcap.northpole.ro/api/v8/bitcoin.json

**Comment by mess110** [comment]
The issue is not 100% fixed because some coins like https://coinmarketcap.com/currencies/quantum-resistant-ledger/ have a long name and coinmarketcap.com adds ... in the name. I didn't see the full name available on https://coinmarketcap.com/all/views/all/ which is where the data is scraped from. So I am not sure how to fully solve this.

**Comment by iwok** [comment]
The main problem ist the symbol and the backslash in the name like in Bitcoin -> "name":"BTC\n Bitcoin"
The dots in the longer coin names are not a problem for me.

**Comment by mess110** [comment]
Fix is currently deploying
